In [ ]:
# 10000 movies

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\ACER\Downloads\mymoviedb.csv",
    engine="python"
)

In [3]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [ ]:
# 18 minutes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB

In [5]:
df.columns

Index(['Release_Date', 'Title', 'Overview', 'Popularity', 'Vote_Count',
       'Vote_Average', 'Original_Language', 'Genre', 'Poster_Url'],
      dtype='object')

In [ ]:
# Release_Date,Vote_Count,Vote_Average = data types are mismatch

In [ ]:
#  first change the datatype of these columns

In [3]:
df['Release_Date']=pd.to_datetime(df['Release_Date'],errors='coerce')

# Use errors='coerce' so pandas: we use this because in our dataset have missing date values

# Converts valid dates ✅
# Converts invalid values (like " - Just Desserts") to NaT

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 691.8+ KB

In [4]:
# Here directly not using astype() because astype is work with :
# Every value is valid
# No text
# No commas
# No NaN

# but in our data have missing value or NaN value that's why not using directly astype()


# here first convert into to_numeric which work with

# Converts valid numbers ✅
# Converts invalid values → NaN ✅

df['Vote_Count'] = pd.to_numeric(df['Vote_Count'], errors='coerce').astype('Int64')

In [5]:
# df['Vote_Average'] = pd.to_numeric(df['Vote_Average'], errors='coerce').astype('int64')
df['Vote_Average'] = pd.to_numeric(df['Vote_Average'], errors='coerce')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9826 non-null   Int64
 5   Vote_Average       9826 non-null   float64
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: Int64(1), datetime64[ns](1), float64(2), object(5)
memory usage: 701.4+ KB

In [4]:
df.shape

(9837, 9)

In [11]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [12]:
df.isnull().sum()

Release_Date         10
Title                 9
Overview              9
Popularity           10
Vote_Count           11
Vote_Average         11
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

# Here we can see only Null records

In [21]:
df[df.isnull().any(axis=1)]

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
1105,2013-10-20,Pixie Hollow Bake Off,Tink challenges Gelata to see who can bake the...,NaN,<NA>,NaN,None,None,None
1106,NaT,None,None,NaN,<NA>,NaN,None,None,None
1107,NaT,None,None,NaN,<NA>,NaN,None,None,None
1108,NaT,None,None,NaN,<NA>,NaN,None,None,None
1109,NaT,None,None,NaN,<NA>,NaN,None,None,None
1110,NaT,None,None,NaN,<NA>,NaN,None,None,None
1111,NaT,None,None,NaN,<NA>,NaN,None,None,None
1112,NaT,None,None,NaN,<NA>,NaN,None,None,None
1113,NaT,None,None,NaN,<NA>,NaN,None,None,None
1114,NaT,None,None,NaN,<NA>,NaN,None,None,None
1115,NaT,61.328,35,7.1,<NA>,NaN,https://image.tmdb.org/t/p/original/6iXYe7AkQ1...,None,None

# Here we are removing that records those fields are null (i am removing that records because there are more than 50% of the data are missing in that fields)

In [6]:

df=df[~df.isnull().any(axis=1)]
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [7]:
df.isnull().sum()

Release_Date         0
Title                0
Overview             0
Popularity           0
Vote_Count           0
Vote_Average         0
Original_Language    0
Genre                0
Poster_Url           0
dtype: int64

In [32]:
df

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...
...,...,...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...
9833,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9834,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9835,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9836,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...

In [8]:
df['Genre'].head()   # remove the whitespace

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: object

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [Release_Date, Title, Overview, Popularity, Vote_Count, Vote_Average, Original_Language, Genre, Poster_Url]
Index: []

In [36]:
df.describe()

                        Release_Date   Popularity   Vote_Count  Vote_Average
count                           9826  9826.000000       9826.0   9826.000000
mean   2006-09-23 04:47:14.276409600    40.323951  1392.943721      6.439467
min              1902-04-17 00:00:00    13.354000          0.0      0.000000
25%              2000-10-17 12:00:00    16.128250        146.0      5.900000
50%              2011-09-12 00:00:00    21.195000        444.0      6.500000
75%              2017-11-22 00:00:00    35.179250       1376.0      7.100000
max              2024-07-03 00:00:00  5083.954000      31077.0     10.000000
std                              NaN   108.879332  2611.303856      1.129797

In [10]:
print(df['Release_Date'].dtypes)

datetime64[ns]

In [ ]:
# i want only year part

In [11]:
df['Release_Year'] = df['Release_Date'].dt.year

In [12]:
df['Release_Year'].dtypes

dtype('int32')

In [40]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,Release_Year
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021

# In this analysis we don't need some columns like Overview, Original_Language,Poster_Url

In [13]:
df.drop('Overview',axis=1,inplace=True)

In [14]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,2021
1,2022-03-01,The Batman,3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,2022
2,2022-02-25,No Exit,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,2022
3,2021-11-24,Encanto,2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,2021
4,2021-12-22,The King's Man,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,2021
...,...,...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...,1973
9833,2020-10-01,Violent Delights,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...,2020
9834,2016-05-06,The Offering,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...,2016
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...,2021
9836,1984-09-23,Threads,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...,1984

In [15]:
col=['Original_Language','Poster_Url']
df.drop(col,axis=1,inplace=True)

In [16]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",2021
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",2022
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller,2022
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy",2021
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War",2021
...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,7.6,"Drama, Crime",1973
9833,2020-10-01,Violent Delights,13.356,8,3.5,Horror,2020
9834,2016-05-06,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror",2016
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History",2021
9836,1984-09-23,Threads,13.354,186,7.8,"War, Drama, Science Fiction",1984

# We would cut the Vote_Average values and make 4 categories : Popular , Average, below_average, not_popular to describe it more.

In [ ]:
# One of the way to add labels in the column but here i didn't run this code

df['Vote_Average']=pd.cut(
    df['Vote_Average'],
    bins=[0,2.5,5,7.5],   # i can give according to me 
    labels=["Not_Popular","below_average","Average","Popular"]
)

In [28]:
df

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,Spider-Man: No Way Home,5083.954,8940,Popular,Action,2021
1,Spider-Man: No Way Home,5083.954,8940,Popular,Adventure,2021
2,Spider-Man: No Way Home,5083.954,8940,Popular,Science Fiction,2021
3,The Batman,3827.658,1151,Popular,Crime,2022
4,The Batman,3827.658,1151,Popular,Mystery,2022
...,...,...,...,...,...,...
25787,The United States vs. Billie Holiday,13.354,152,Average,Drama,2021
25788,The United States vs. Billie Holiday,13.354,152,Average,History,2021
25789,Threads,13.354,186,Popular,War,1984
25790,Threads,13.354,186,Popular,Drama,1984
25791,Threads,13.354,186,Popular,Science Fiction,1984

In [88]:
# Show only Popular 

df[df['Vote_Average']=='Popular']

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Action,2021.0
1,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Adventure,2021.0
2,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Science Fiction,2021.0
3,2022-03-01,The Batman,3827.658,1151,Popular,Crime,2022.0
4,2022-03-01,The Batman,3827.658,1151,Popular,Mystery,2022.0
...,...,...,...,...,...,...,...
25791,1973-10-15,Badlands,13.357,896,Popular,Drama,1973.0
25792,1973-10-15,Badlands,13.357,896,Popular,Crime,1973.0
25800,1984-09-23,Threads,13.354,186,Popular,War,1984.0
25801,1984-09-23,Threads,13.354,186,Popular,Drama,1984.0
25802,1984-09-23,Threads,13.354,186,Popular,Science Fiction,1984.0

# Agar percentage ke basis par karna hai jaise ki 25%,50%,75% or 100% ke basis par uske liye ham ek function ka use karte hai jisse kaam easy ho jayega

In [19]:
def categorize_column(df,col,label):
    edges=[
        df[col].describe()['min'],
        df[col].describe()['25%'],
        df[col].describe()['50%'],
        df[col].describe()['75%'],
        df[col].describe()['max']
    ]

    df[col]=pd.cut(df[col],edges,labels=label,duplicates='drop')
    return df

In [20]:
label=["Not_Popular","below_average","Average","Popular"]

categorize_column(df,'Vote_Average',label)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,"Action, Adventure, Science Fiction",2021
1,2022-03-01,The Batman,3827.658,1151,Popular,"Crime, Mystery, Thriller",2022
2,2022-02-25,No Exit,2618.087,122,below_average,Thriller,2022
3,2021-11-24,Encanto,2402.201,5076,Popular,"Animation, Comedy, Family, Fantasy",2021
4,2021-12-22,The King's Man,1895.511,1793,Average,"Action, Adventure, Thriller, War",2021
...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,Popular,"Drama, Crime",1973
9833,2020-10-01,Violent Delights,13.356,8,Not_Popular,Horror,2020
9834,2016-05-06,The Offering,13.355,94,Not_Popular,"Mystery, Thriller, Horror",2016
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,Average,"Music, Drama, History",2021
9836,1984-09-23,Threads,13.354,186,Popular,"War, Drama, Science Fiction",1984

In [47]:
df

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,"Action, Adventure, Science Fiction",2021
1,2022-03-01,The Batman,3827.658,1151,Popular,"Crime, Mystery, Thriller",2022
2,2022-02-25,No Exit,2618.087,122,below_average,Thriller,2022
3,2021-11-24,Encanto,2402.201,5076,Popular,"Animation, Comedy, Family, Fantasy",2021
4,2021-12-22,The King's Man,1895.511,1793,Average,"Action, Adventure, Thriller, War",2021
...,...,...,...,...,...,...,...
9832,1973-10-15,Badlands,13.357,896,Popular,"Drama, Crime",1973
9833,2020-10-01,Violent Delights,13.356,8,Not_Popular,Horror,2020
9834,2016-05-06,The Offering,13.355,94,Not_Popular,"Mystery, Thriller, Horror",2016
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,Average,"Music, Drama, History",2021
9836,1984-09-23,Threads,13.354,186,Popular,"War, Drama, Science Fiction",1984

# we would split genre into a list and then explore our datafraame to have only one genre per row for each movie

In [21]:
df['Genre']=df['Genre'].str.strip()    # strip is used for remove only white spaces

# if want to remove white space along with comma then use split function

In [22]:
df['Genre']=df['Genre'].str.split(', ')
df=df.explode('Genre').reset_index(drop=True)  # isme jo genre ka column hai usme multiple value ek hi column me hai ham chahte hai ki sab alag alag column me aaye uske liye explode() function ka use kiya
df.head()   # use reset_index because i want all the records of that films of Genre at the same continuous that means one by one record of that film.

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Action,2021
1,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Adventure,2021
2,2021-12-15,Spider-Man: No Way Home,5083.954,8940,Popular,Science Fiction,2021
3,2022-03-01,The Batman,3827.658,1151,Popular,Crime,2022
4,2022-03-01,The Batman,3827.658,1151,Popular,Mystery,2022

In [16]:
df.shape

(25792, 7)

In [23]:
df.nunique()

Release_Date    5892
Title           9512
Popularity      8159
Vote_Count      3266
Vote_Average       4
Genre             19
Release_Year     102
dtype: int64

In [24]:
# casting column into category

df['Genre']=df['Genre'].astype("category")
df['Genre'].dtypes

CategoricalDtype(categories=['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
                  'Documentary', 'Drama', 'Family', 'Fantasy', 'History',
                  'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
                  'TV Movie', 'Thriller', 'War', 'Western'],
, ordered=False, categories_dtype=object)

In [ ]:
# Here remove Release_Date because we don't need of it any more. We will only work with the Release_Year

In [25]:
df.drop('Release_Date',axis=1,inplace=True)

In [54]:
df.head()

,Title,Popularity,Vote_Count,Vote_Average,Genre,Release_Year
0,Spider-Man: No Way Home,5083.954,8940,Popular,Action,2021
1,Spider-Man: No Way Home,5083.954,8940,Popular,Adventure,2021
2,Spider-Man: No Way Home,5083.954,8940,Popular,Science Fiction,2021
3,The Batman,3827.658,1151,Popular,Crime,2022
4,The Batman,3827.658,1151,Popular,Mystery,2022